### ISSUE TITLE
Bridging Issue

### ISSUE THREAD

**Issue by reyserveth** [safe-global/safe-services-status#376]
My case is complicated: I used Safe, and got into the Superfluid inside the Safe, then I used the Bridge in it(Li.Fi). Then I bridged my USDC on Arbitrium to Optimism. However, it seems that the USDC in that address are not really on OP chain and it's a kind of OP version's USDC on Arb address so that I cannot just send it to my another wallet.
Then I tried another way, I used the Li.Fi again to bridge the USDC from Op back to Arb. However, I couldn't bridge it back since it shows that I need to switch chains to OP. But if I switch to OP, the safe's address will change.

My main wallet address: 0xc83c3B46D8E622b9C7b540872c6AF8636DdC1D17
②My Safe’s address on Arb： 0xA9aA585E499d02FbDd492cF4928e4C988dB1855B
③My safe's address on Op: 0x6B7870c45268b38b162BCC57C470b5d572c21d1A

**Comment by med3000** [comment]
@reyserveth pls use https://github.com/5afe/safe-support

**Comment by carlosmily** [comment]
> @reyserveth pls use https://github.com/5afe/safe-support

Thanks a lot. Let me add more information : 
Now the USDC is on OP chain (https://optimistic.etherscan.io/address/0xa9aa585e499d02fbdd492cf4928e4c988db1855b#tokentxns). But I cannot control it since my Safe address on OP is different from that of on Arb. So is there any possibility that Safe can give me the control of 0xa9aa585e499d02fbdd492cf4928e4c988db1855b on OP?（now I only have the control of this addresss on Arb）

**Comment by reyserveth** [comment]
Transferred already. Thank you
